
GET http://localhost:3000/movies/

### 

POST http://localhost:3000/movies/
Content-Type: application/json

{
    "directorId":6,
    "movieName":"Jurrasic Park",
    "leadActor":"Jeff Goldblum"
}

###
GET http://localhost:3000/movies/62/

###
PUT http://localhost:3000/movies/62/
Content-Type: application/json

{
    "directorId":24,
    "movieName":"Thor",
    "leadActor":"Christoher Hemsworth"
}

###
DELETE http://localhost:3000/movies/63/

###
GET http://localhost:3000/directors/

###
GET http://localhost:3000/directors/37/movies/




